server:
  port: 8085
  servlet:
    context-path: /services/be/notification-service

  address: 0.0.0.0

notifications:
  credentials:
    path: ${SERVICE_ACCOUNT_KEY_PATH}

kafka:
    group:
      id: "group"
    topic:
      name: "notification-topic"

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: codemirror17@gmail.com
    password: olwjkegubzdcdwup
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


doc:
  api:
    path: /doc/api
    title: Notification API
    description: Documentation for the notification API
    version: 1.0.0
